"""SDK-owned named JSON Schema formats — Goldenrod.2 FC-1.5.

A small set of URL/path grammars are shared across SDK-bundled filters. Rather
than decompose each into a tagged-union ``BaseModel``, we ship them as
**named JSON Schema ``format:`` values** with vendored validators on both
sides — this module is the Python half. The Go half lives in
``plainsight-api/internal/schema/formats``.

Filters declare leaves; URLs stay strings; the named format carries the
contract:

    from openfilter.filter_runtime.formats import VideoSource

    class FilterVideoInConfig(FilterConfigBase):
        sources: list[VideoSource]

The emitted schema for that field is::

    {"type": "array", "items": {"type": "string", "format": "video-source"}}

Initial 1.0 membership is ``openfilter-source`` and ``video-source``.
Additional formats land as bundled-filter migrations under FC-10 force them.
"""

from __future__ import annotations

import re
from typing import Annotated
from urllib.parse import urlparse

from pydantic import AfterValidator, GetJsonSchemaHandler
from pydantic.json_schema import JsonSchemaValue
from pydantic_core import CoreSchema

__all__ = [
    "OpenfilterSource",
    "VideoSource",
    "validate_openfilter_source",
    "validate_video_source",
    "VIDEO_SOURCE_SCHEMES",
]


# --- openfilter-source ---------------------------------------------------------

# Wire-protocol URL: tcp://host:port[;src-topic[>tgt-topic]] or ipc://path[;topic]
# Topic + remap are optional; many edges in autogenerated graphs carry them.
# Topic chars: alphanumerics, dash, underscore, dot, slash.
_TOPIC_CHARS = r"[A-Za-z0-9_\-./]+"
_OPENFILTER_SOURCE_RE = re.compile(
    rf"^(?P<scheme>tcp|ipc)://(?P<addr>[^;]+)"
    rf"(?:;(?P<src>{_TOPIC_CHARS})(?:>(?P<tgt>{_TOPIC_CHARS}))?)?$"
)


def validate_openfilter_source(value: str) -> str:
    """Validate an openfilter-source URL.

    Grammar: ``tcp://host:port[;src-topic[>tgt-topic]]`` or ``ipc://path[;topic]``.
    Returns the value unchanged on success; raises ``ValueError`` otherwise.
    """
    if not isinstance(value, str):
        raise ValueError("openfilter-source must be a string")
    if not _OPENFILTER_SOURCE_RE.match(value):
        raise ValueError(
            f"not a valid openfilter-source URL: {value!r} "
            f"(expected tcp://host:port[;src>tgt] or ipc://path[;topic])"
        )
    return value


# --- video-source --------------------------------------------------------------

VIDEO_SOURCE_SCHEMES = frozenset(
    {"rtsp", "file", "webcam", "tcp", "gs", "http", "https"}
)


def validate_video_source(value: str) -> str:
    """Validate a video-source URL.

    Accepts any of: ``rtsp://``, ``file://``, ``webcam://``, ``tcp://``,
    ``gs://``, ``http(s)://``. Per-scheme shape rules are intentionally
    minimal at this stage — they tighten as bundled-filter migrations under
    FC-10 surface real edge cases.
    """
    if not isinstance(value, str):
        raise ValueError("video-source must be a string")
    parsed = urlparse(value)
    scheme = parsed.scheme.lower()
    if scheme not in VIDEO_SOURCE_SCHEMES:
        raise ValueError(
            f"not a valid video-source URL: {value!r} "
            f"(unsupported scheme {scheme!r}; expected one of "
            f"{sorted(VIDEO_SOURCE_SCHEMES)})"
        )
    if scheme == "webcam":
        if not (parsed.netloc or parsed.path):
            raise ValueError(f"webcam:// must carry an index or device: {value!r}")
        return value
    if scheme == "file":
        if not (parsed.netloc or parsed.path):
            raise ValueError(f"file:// must carry a path: {value!r}")
        return value
    if scheme == "gs":
        if not parsed.netloc:
            raise ValueError(f"gs:// must carry a bucket: {value!r}")
        return value
    if not parsed.netloc:
        raise ValueError(f"{scheme}:// must carry a host: {value!r}")
    return value


# --- pydantic plumbing ---------------------------------------------------------

class _NamedFormat:
    """Annotation that injects ``format:`` into the emitted JSON Schema.

    pydantic's ``AfterValidator`` carries the validator; this class carries
    the schema-emission side so a string with a ``format`` keyword survives
    ``model_json_schema()``.
    """

    def __init__(self, format_name: str) -> None:
        self.format_name = format_name

    def __get_pydantic_json_schema__(
        self, schema: CoreSchema, handler: GetJsonSchemaHandler
    ) -> JsonSchemaValue:
        json_schema = handler(schema)
        json_schema["format"] = self.format_name
        return json_schema


OpenfilterSource = Annotated[
    str,
    AfterValidator(validate_openfilter_source),
    _NamedFormat("openfilter-source"),
]
"""ZMQ wire-protocol URL: ``tcp://host:port[;src-topic[>tgt-topic]]`` or ``ipc://path[;topic]``."""


VideoSource = Annotated[
    str,
    AfterValidator(validate_video_source),
    _NamedFormat("video-source"),
]
"""Video source URL — ``rtsp://`` / ``file://`` / ``webcam://`` / ``tcp://`` / ``gs://`` / ``http(s)://``."""
