# OpenFilter Comprehensive Configuration
# This file contains both safe metrics allowlist and OpenLineage configuration

# OpenLineage Configuration
openlineage:
  url: "https://oleander.dev"
  api_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdhbml6YXRpb25JZCI6IjMyMjhmYTA4LTRjNDUtNDRjMi1hNTk4LWQ2YTIyZDk3MmI0NiIsImlhdCI6MTc0MzgwNTgyNn0.GBhz5qyY8Ffep8_GJE1meeibS04vk8ADwVGzAGdoP-0"
  heartbeat_interval: 5  # seconds

# Safe Metrics Allowlist
# Only metrics listed here will be exported to OpenLineage
safe_metrics:
  # Frame processing metrics
  - frames_processed
  - frames_with_detections
  
  # Detection histograms (base names - bridge will add _histogram suffix)
  - detections_per_frame
  - detection_confidence
  - processing_time_ms
  
  # Object analysis metrics
  - object_size_ratio
  
  # System metrics (wildcards supported)
  - customprocessor_*
  - customvisualizer_*
  
  # Additional metrics for testing
  - "*_fps"
  - "*_cpu"
  - "*_mem"

# Alternative minimal configuration for production:
# safe_metrics:
#   - frames_processed
#   - frames_with_detections
#   - customprocessor_fps
#   - customprocessor_cpu
